- name: reload postfix
  service:
    name: postfix
    state: reloaded

- name: update newalias
  command: '/usr/bin/newaliases'

- name: update relay_password DB
  shell: "rm -f /etc/postfix/relay_password.db; sleep 1; /usr/sbin/postmap hash:/etc/postfix/relay_password"

- name: update generic map
  shell: "rm -f /etc/postfix/generic.db; sleep 1; /usr/sbin/postmap hash:/etc/postfix/generic"
